# Generated by Django 3.2.5 on 2021-07-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dongoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='rating',
            field=models.FloatField(default=3.3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.CharField(max_length=10000),
        ),
    ]
